version: "3.8"

services:
  backend:
    build:
      context: ./backend/myapi
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/myapi:/app
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4